name: Deploy Docs to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs.yaml'
  workflow_dispatch:

env:
  PACKAGE_NAME: "super_slurpy"
  OWNER: "Pertti Palo"
  
# Give the action permission to push to the gh-pages branch
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "docs-build-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Set up Python
        run: uv python install

      - name: Install project and dependencies
        run: uv sync --all-extras

      - name: Build Sphinx Docs
        working-directory: docs
        run: make gen-docs

      - name: Deploy to GitHub Pages (latest)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages             # Explicitly telling it where to push
          folder: docs/build/html      # The folder we built the HTML into
          target-folder: latest        # The subfolder on the branch to put it in
          clean: false                 # Do not delete existing versions!